print("FACEBOOK Registro")
print("Datos a ingresar: ")
print("Nombre: ")
nombre=input()
print("Apellido: ")
apellido=input()
print("Email: ")
correo=input()
print("Fecha de cumpleaños: ")
fecha=str(input())
print("Sexo: ")
sex= input()
print("Contraseña: ")
contr=int(input())
print("Ya estas registrado...")
